defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: py-txi
  - _base_
  - _self_

name: tgi

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: True
  model: TinyLlama/TinyLlama-1.1B-Chat-v1.0

scenario:
  energy: true
  memory: true
  latency: true
  input_shapes:
    batch_size: 1
    sequence_length: 256
  generate_kwargs:
    max_new_tokens: 256
    min_new_tokens: 256
